[package]
name = "parco-xml-test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
parco-xml = { version = "0.2.1", path = "../parco-xml" }
serde = { version = "1.0.228", features = ["derive"] }
